services:
  mongodb:
    # The latest version that can work WITHOUT AVX is image: mongo:4.4.18
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p toshiba-mongodb up -d
